### ISSUE TITLE
新增 docker-compose 部署方式

### ISSUE THREAD

**Issue by markwhitey** [nianhua99/PandoraNext-Helper#59]
```yml
version: '3.3'
services:
  pandoranext-helper:
    image: q11391/pandora-next-helper
    container_name: PandoraNext-Helper
    restart: always
    network_mode: bridge
    ports:
      - "8182:8182"
    volumes:
      - <YOUR_PANDORA_NEXT_PATH>:/data
    environment:
      - PANDORA_NEXT_DOMAIN=<YOUR_PANDORA_NEXT_DOMAIN>
```
